#!/bin/bash

ROOT="$1"

if [[ ! -f $ROOT/tmp/solr.pid ]]; then
    echo "Solr is not currently running"
    rm -f $ROOT/tmp/solr.out
    exit
fi

kill `cat $ROOT/tmp/solr.pid`
rm -f $ROOT/tmp/solr.pid $ROOT/tmp/solr.out
