#!/bin/bash

ROOT="$1"

cd $ROOT/contrib/solr/example
java -jar winstone.jar --warfile=solr.war --httpPort=8983 --httpListenAddress=127.0.0.1 > $ROOT/tmp/solr.out 2>&1 &

echo $! > $ROOT/tmp/solr.pid
sleep 0.5

while read line; do
    if [[ $line == *HTTP\ Listener\ started:\ port=8080 ]]; then
        echo "Solr server started successfully"
        break
    fi
done <$ROOT/tmp/solr.out
